#!/bin/bash

defitem_settings=1

while true; do
dialog_menu_item $defitem_settings "Settings" "" \
"1" "Dynarec settings" \
"2" "Wine prefix settings (+ESYNC)" \
"3" "DXVK settings" \
"4" "System settings" \
"5" "Debug settings" \
"6" "Root settings" \
"7" "VirGL settings" \
"8" "Backup and restore" \
"9" "Device compatibility settings"
defitem_settings=$?
case $defitem_settings in
1)
	. $PREFIX/glibc/opt/conf/dynarec_preset.conf
	if [ "$DYNAREC_SETTINGS_SCRIPT" = "1" ]; then
		. $PREFIX/glibc/opt/scripts/custom-dynarec-settings
	else
		. $PREFIX/glibc/opt/scripts/dynarec2-settings
	fi
;;
2)
	. $PREFIX/glibc/opt/scripts/prefix-settings
;;
3)
	. $PREFIX/glibc/opt/scripts/dxvk-settings
;;
4)
	. $PREFIX/glibc/opt/scripts/custom-system-settings
;;
5)
	defitem=1
	while true; do
	load_configs
	dialog_menu_item $defitem "Debug settings" "\ZbCurrent settings:\Zn
	\Z3MESA_NO_ERROR\Z2=\Zn$MESA_NO_ERROR
	\Z3WINEDEBUG\Z2=\Zn$WINEDEBUG
	\Z3BOX64_LOG\Z2=\Zn$BOX64_LOG
	\Z3BOX64_SHOWSEGV\Z2=\Zn$BOX64_SHOWSEGV
	\Z3BOX64_DLSYM_ERROR\Z2=\Zn$BOX64_DLSYM_ERROR
	\Z3BOX64_DYNAREC_MISSING\Z2=\Zn$BOX64_DYNAREC_MISSING\Zn" \
"1" "Disable debug" \
"2" "Enable debug ($LOG_PATH)" \
"3" "Enable detailed debug ($LOG_PATH)"
	defitem=$?
	case $defitem in
	1) echo "export DEBUG_MODE=0">$PREFIX/glibc/opt/conf/debug.conf ;;
	2) echo "export DEBUG_MODE=1">$PREFIX/glibc/opt/conf/debug.conf ;;
	3) echo "export DEBUG_MODE=2">$PREFIX/glibc/opt/conf/debug.conf ;;
	255) break ;;
	esac
	done
;;
6)
	. $PREFIX/glibc/opt/scripts/root-settings
;;
7)
	. $PREFIX/glibc/opt/scripts/virgl-settings
;;
8)
	. $PREFIX/glibc/opt/scripts/restore-menu
;;
9)
	. $PREFIX/glibc/opt/scripts/compatibility-settings
;;
255)
	break
;;
esac
done
