#!/bin/bash

defitem=1

while true; do
load_configs
dialog_menu_item $defitem "Dynarec presets" "\ZbCurrent settings:\Zn
  \Z3DYNAREC_ALIGNED_ATOMICS \Z2= \Zn$BOX64_DYNAREC_ALIGNED_ATOMICS
  \Z3BOX64_DYNAREC_BIGBLOCK \Z2= \Zn$BOX64_DYNAREC_BIGBLOCK
  \Z3DYNAREC_FASTNAN \Z2= \Zn$BOX64_DYNAREC_FASTNAN
  \Z3DYNAREC_SAFEFLAGS \Z2= \Zn$BOX64_DYNAREC_SAFEFLAGS
  \Z3DYNAREC_STRONGMEM \Z2= \Zn$BOX64_DYNAREC_STRONGMEM
  \Z3DYNAREC_WAIT \Z2= \Zn$BOX64_DYNAREC_WAIT
  \Z3DYNAREC_X87DOUBLE \Z2= \Zn$BOX64_DYNAREC_X87DOUBLE
  \Z3DYNAREC_CALLRET \Z2= \Zn$BOX64_DYNAREC_CALLRET
  \Z3IGNOREINT3 \Z2= \Zn$BOX64_IGNOREINT3

  \Z3$(sed '4q;d' $DXVK_CONFIG_FILE)\Zn
  \Z3FALLBACK RESOLUTION\Z2=\Zn$(cat $PREFIX/glibc/opt/last-resolution.conf)\Zn
  
  \Z3Current Preset\Z2=\Zn$(cat $PREFIX/glibc/opt/custom-preset-current.conf)\Zn" \
    "1" "Resident Evil 6" \
	"2" "TES-IV Oblivion" \
	"3" "Alone In The Dark (2008)" \
	"4" "Mass Effect" \
	"5" "Call of Duty: Modern Warfare" \
	" " " " \
	"200" "Resolution changing $DYNAREC_PRESET_RESOLUTION_SWITCH" \
	"201" "Max framerate changing $DYNAREC_PRESET_FPS_SWITCH" \

defitem=$?
case $defitem in
1)
	echo "unset BOX64_DYNAREC_ALIGNED_ATOMICS">$PREFIX/glibc/opt/conf/dynarec/aligned_atomics.conf
	echo "export BOX64_DYNAREC_BIGBLOCK=2">$PREFIX/glibc/opt/conf/dynarec/bigblock.conf
	echo "export BOX64_DYNAREC_FASTNAN=1">$PREFIX/glibc/opt/conf/dynarec/fastnan.conf
	echo "export BOX64_DYNAREC_SAFEFLAGS=2">$PREFIX/glibc/opt/conf/dynarec/safeflags.conf
	echo "export BOX64_DYNAREC_STRONGMEM=0">$PREFIX/glibc/opt/conf/dynarec/strongmem.conf
	echo "export BOX64_DYNAREC_WAIT=1">$PREFIX/glibc/opt/conf/dynarec/wait.conf
	echo "export BOX64_DYNAREC_X87DOUBLE=0">$PREFIX/glibc/opt/conf/dynarec/x87double.conf
	echo "export BOX64_DYNAREC_CALLRET=1">$PREFIX/glibc/opt/conf/dynarec/callret.conf
	echo "unset BOX64_DYNAREC_FASTROUND">$PREFIX/glibc/opt/conf/dynarec/fastround.conf
	echo "unset BOX64_IGNOREINT3">$PREFIX/glibc/opt/conf/dynarec/ignoreint3.conf
	if [ "$DYNAREC_PRESET_RESOLUTION_SWITCH" = "enabled" ]; then
		echo "848x480">$PREFIX/glibc/opt/last-resolution.conf
	fi
	if [ "$DYNAREC_PRESET_FPS_SWITCH" = "enabled" ]; then
		sed -i '4s/.*/dxgi.maxFrameRate = 32/' $DXVK_CONFIG_FILE
		sed -i '5s/.*/d3d9.maxFrameRate = 32/' $DXVK_CONFIG_FILE
	fi
	echo "Resident Evil 6">$PREFIX/glibc/opt/custom-preset-current.conf
;;
2)
	echo "unset BOX64_DYNAREC_ALIGNED_ATOMICS">$PREFIX/glibc/opt/conf/dynarec/aligned_atomics.conf
	echo "export BOX64_DYNAREC_BIGBLOCK=2">$PREFIX/glibc/opt/conf/dynarec/bigblock.conf
	echo "export BOX64_DYNAREC_FASTNAN=1">$PREFIX/glibc/opt/conf/dynarec/fastnan.conf
	echo "export BOX64_DYNAREC_SAFEFLAGS=0">$PREFIX/glibc/opt/conf/dynarec/safeflags.conf
	echo "export BOX64_DYNAREC_STRONGMEM=0">$PREFIX/glibc/opt/conf/dynarec/strongmem.conf
	echo "unset BOX64_DYNAREC_WAIT">$PREFIX/glibc/opt/conf/dynarec/wait.conf
	echo "export BOX64_DYNAREC_X87DOUBLE=1">$PREFIX/glibc/opt/conf/dynarec/x87double.conf
	echo "export BOX64_DYNAREC_CALLRET=0">$PREFIX/glibc/opt/conf/dynarec/callret.conf
	echo "unset BOX64_DYNAREC_FASTROUND">$PREFIX/glibc/opt/conf/dynarec/fastround.conf
	echo "unset BOX64_IGNOREINT3">$PREFIX/glibc/opt/conf/dynarec/ignoreint3.conf
	if [ "$DYNAREC_PRESET_RESOLUTION_SWITCH" = "enabled" ]; then
		echo "848x480">$PREFIX/glibc/opt/last-resolution.conf
	fi
	if [ "$DYNAREC_PRESET_FPS_SWITCH" = "enabled" ]; then
		sed -i '4s/.*/dxgi.maxFrameRate = 45/' $DXVK_CONFIG_FILE
		sed -i '5s/.*/d3d9.maxFrameRate = 45/' $DXVK_CONFIG_FILE
	fi
	echo "TES-IV Oblivion">$PREFIX/glibc/opt/custom-preset-current.conf
;;
3)
	echo "export BOX64_DYNAREC_ALIGNED_ATOMICS=1">$PREFIX/glibc/opt/conf/dynarec/aligned_atomics.conf
	echo "export BOX64_DYNAREC_BIGBLOCK=1">$PREFIX/glibc/opt/conf/dynarec/bigblock.conf
	echo "export BOX64_DYNAREC_FASTNAN=1">$PREFIX/glibc/opt/conf/dynarec/fastnan.conf
	echo "unset BOX64_DYNAREC_SAFEFLAGS">$PREFIX/glibc/opt/conf/dynarec/safeflags.conf
	echo "unset BOX64_DYNAREC_STRONGMEM">$PREFIX/glibc/opt/conf/dynarec/strongmem.conf
	echo "unset BOX64_DYNAREC_WAIT">$PREFIX/glibc/opt/conf/dynarec/wait.conf
	echo "export BOX64_DYNAREC_X87DOUBLE=1">$PREFIX/glibc/opt/conf/dynarec/x87double.conf
	echo "export BOX64_DYNAREC_CALLRET=1">$PREFIX/glibc/opt/conf/dynarec/callret.conf
	echo "export BOX64_DYNAREC_FASTROUND=1">$PREFIX/glibc/opt/conf/dynarec/fastround.conf
	echo "unset BOX64_IGNOREINT3">$PREFIX/glibc/opt/conf/dynarec/ignoreint3.conf
	if [ "$DYNAREC_PRESET_RESOLUTION_SWITCH" = "enabled" ]; then
		echo "848x480">$PREFIX/glibc/opt/last-resolution.conf
	fi
	if [ "$DYNAREC_PRESET_FPS_SWITCH" = "enabled" ]; then
		sed -i '4s/.*/dxgi.maxFrameRate = 35/' $DXVK_CONFIG_FILE
		sed -i '5s/.*/d3d9.maxFrameRate = 35/' $DXVK_CONFIG_FILE
	fi
	echo "Alone In The Dark (2008)">$PREFIX/glibc/opt/custom-preset-current.conf
;;
4)
	echo "unset BOX64_DYNAREC_ALIGNED_ATOMICS">$PREFIX/glibc/opt/conf/dynarec/aligned_atomics.conf
	echo "export BOX64_DYNAREC_BIGBLOCK=2">$PREFIX/glibc/opt/conf/dynarec/bigblock.conf
	echo "unset BOX64_DYNAREC_FASTNAN">$PREFIX/glibc/opt/conf/dynarec/fastnan.conf
	echo "export BOX64_DYNAREC_SAFEFLAGS=0">$PREFIX/glibc/opt/conf/dynarec/safeflags.conf
	echo "export BOX64_DYNAREC_STRONGMEM=1">$PREFIX/glibc/opt/conf/dynarec/strongmem.conf
	echo "unset BOX64_DYNAREC_WAIT">$PREFIX/glibc/opt/conf/dynarec/wait.conf
	echo "export BOX64_DYNAREC_X87DOUBLE=1">$PREFIX/glibc/opt/conf/dynarec/x87double.conf
	echo "export BOX64_DYNAREC_CALLRET=1">$PREFIX/glibc/opt/conf/dynarec/callret.conf
	echo "unset BOX64_DYNAREC_FASTROUND">$PREFIX/glibc/opt/conf/dynarec/fastround.conf
	echo "unset BOX64_IGNOREINT3">$PREFIX/glibc/opt/conf/dynarec/ignoreint3.conf
	if [ "$DYNAREC_PRESET_RESOLUTION_SWITCH" = "enabled" ]; then
		echo "848x480">$PREFIX/glibc/opt/last-resolution.conf
	fi
	if [ "$DYNAREC_PRESET_FPS_SWITCH" = "enabled" ]; then
		sed -i '4s/.*/dxgi.maxFrameRate = 32/' $DXVK_CONFIG_FILE
		sed -i '5s/.*/d3d9.maxFrameRate = 32/' $DXVK_CONFIG_FILE
	fi
	echo "Mass Effect">$PREFIX/glibc/opt/custom-preset-current.conf
;;
5)
	echo "unset BOX64_DYNAREC_ALIGNED_ATOMICS">$PREFIX/glibc/opt/conf/dynarec/aligned_atomics.conf
	echo "export BOX64_DYNAREC_BIGBLOCK=2">$PREFIX/glibc/opt/conf/dynarec/bigblock.conf
	echo "unset BOX64_DYNAREC_FASTNAN">$PREFIX/glibc/opt/conf/dynarec/fastnan.conf
	echo "export BOX64_DYNAREC_SAFEFLAGS=2">$PREFIX/glibc/opt/conf/dynarec/safeflags.conf
	echo "unset BOX64_DYNAREC_STRONGMEM">$PREFIX/glibc/opt/conf/dynarec/strongmem.conf
	echo "unset BOX64_DYNAREC_WAIT">$PREFIX/glibc/opt/conf/dynarec/wait.conf
	echo "unset BOX64_DYNAREC_X87DOUBLE">$PREFIX/glibc/opt/conf/dynarec/x87double.conf
	echo "export BOX64_DYNAREC_CALLRET=1">$PREFIX/glibc/opt/conf/dynarec/callret.conf
	echo "unset BOX64_DYNAREC_FASTROUND">$PREFIX/glibc/opt/conf/dynarec/fastround.conf
	echo "unset BOX64_IGNOREINT3">$PREFIX/glibc/opt/conf/dynarec/ignoreint3.conf
	if [ "$DYNAREC_PRESET_RESOLUTION_SWITCH" = "enabled" ]; then
		echo "848x480">$PREFIX/glibc/opt/last-resolution.conf
	fi
	if [ "$DYNAREC_PRESET_FPS_SWITCH" = "enabled" ]; then
		sed -i '4s/.*/dxgi.maxFrameRate = 45/' $DXVK_CONFIG_FILE
		sed -i '5s/.*/d3d9.maxFrameRate = 45/' $DXVK_CONFIG_FILE
	fi
	echo "Call of Duty: Modern Warfare">$PREFIX/glibc/opt/custom-preset-current.conf
;;
200)
	if [ "$DYNAREC_PRESET_RESOLUTION_SWITCH" = "enabled" ]; then
		echo "export DYNAREC_PRESET_RESOLUTION_SWITCH=disabled">$PREFIX/glibc/opt/conf/custom-preset-resolution.conf
	else
		echo "export DYNAREC_PRESET_RESOLUTION_SWITCH=enabled">$PREFIX/glibc/opt/conf/custom-preset-resolution.conf
	fi
;;
201)
	if [ "$DYNAREC_PRESET_FPS_SWITCH" = "enabled" ]; then
		echo "export DYNAREC_PRESET_FPS_SWITCH=disabled">$PREFIX/glibc/opt/conf/custom-preset-fps.conf
	else
		echo "export DYNAREC_PRESET_FPS_SWITCH=enabled">$PREFIX/glibc/opt/conf/custom-preset-fps.conf
	fi
;;
255)
	break
;;
esac
done
