#!/bin/bash

defitem=1

while true; do
load_configs
dialog_menu_item $defitem "System settings" "\ZbCurrent settings:\Zn
	\Z3PRIMARY_CORES\Z2=\Zn$PRIMARY_CORES
	\Z3SECONDARY_CORES\Z2=\Zn$SECONDARY_CORES
	\Z3LOCALE\Z2=\Zn$(cat $PREFIX/glibc/opt/locale.conf)
	\Z3DXVK_HUD\Z2=\Zn$DXVK_HUD
	\Z3GALLIUM_HUD\Z2=\Zn$GALLIUM_HUD
	\Z3TU_DEBUG\Z2=\Zn$TU_DEBUG
	\Z3MESA_VK_WSI_PRESENT_MODE\Z2=\Zn$MESA_VK_WSI_PRESENT_MODE
	\Z3FALLBACK RESOLUTION\Z2=\Zn$(cat $PREFIX/glibc/opt/last-resolution.conf)\Zn" \
	"1" "Change fallback resolution" \
	"2" "Change primary cores amount" \
	"3" "Change locale" \
	"4" "Change HUD preset" \
	"5" "Select TU_DEBUG" \
	"6" "Reset to default"
defitem=$?
case $defitem in
1)
	dialog_menu "" "Select new resolution." \
	"1" "Custom resolution" \
	"2" "848x480    (16:9)" \
	"3" "1280x720   (16:9)" \
	"4" "1280x1024   (5:4)" \
	"5" "800x480     (5:3)" \
	"6" "800x600     (4:3)" \
	"7" "1024x768    (4:3)" \
	"8" "1280x960    (4:3)" 
	case $? in
	1)
	i=$(dialog_inputbox "Enter new fallback resolution (e.g. 1280x720)")
	if [ $? = 1 ] || [ "$i" = "" ]; then continue; fi
	echo "$i">$PREFIX/glibc/opt/last-resolution.conf
	;;
	2)	
	echo "848x480">$PREFIX/glibc/opt/last-resolution.conf;;
	3)	
	echo "1280x720">$PREFIX/glibc/opt/last-resolution.conf;;
	4)	
	echo "1280x1024">$PREFIX/glibc/opt/last-resolution.conf;;
	5)	
	echo "800x480">$PREFIX/glibc/opt/last-resolution.conf;;
	6)	
	echo "800x600">$PREFIX/glibc/opt/last-resolution.conf;;
	7)	
	echo "1024x768">$PREFIX/glibc/opt/last-resolution.conf;;
	8)	
	echo "1280x960">$PREFIX/glibc/opt/last-resolution.conf;;
	esac
;;
2)
	dialog_menu "" "Select new amount of cores you want to use. (default - 7, any value from 2 to 7)" \
	"2" "primary cores" \
	"3" "primary cores" \
	"4" "primary cores" \
	"5" "primary cores" \
	"6" "primary cores" \
	"7" "primary cores" \
	"8" "primary cores"
	case $? in
	2) echo "export PRIMARY_CORES=6-7
export SECONDARY_CORES=0-5">$PREFIX/glibc/opt/conf/cores.conf ;;
	3) echo "export PRIMARY_CORES=5-7
export SECONDARY_CORES=0-4">$PREFIX/glibc/opt/conf/cores.conf ;;
	4) echo "export PRIMARY_CORES=4-7
export SECONDARY_CORES=0-3">$PREFIX/glibc/opt/conf/cores.conf ;;
	5) echo "export PRIMARY_CORES=3-7
export SECONDARY_CORES=0-2">$PREFIX/glibc/opt/conf/cores.conf ;;
	6) echo "export PRIMARY_CORES=2-7
export SECONDARY_CORES=0-1">$PREFIX/glibc/opt/conf/cores.conf ;;
	7) echo "export PRIMARY_CORES=1-7
export SECONDARY_CORES=0-1">$PREFIX/glibc/opt/conf/cores.conf ;;
	8) echo "export PRIMARY_CORES=0-7
export SECONDARY_CORES=0-1">$PREFIX/glibc/opt/conf/cores.conf ;;
	
	esac
;;
3)
	i=$(dialog_inputbox "Enter new locale. (e.g. en_US)")
	if [ $? = 1 ] || [ "$i" = "" ]; then continue; fi
	echo "$i.utf8">$PREFIX/glibc/opt/locale.conf
;;
4)
	dialog_menu "" "" \
"1" "Disable gallium and dxvk hud" \
"2" "Enable fps counter" \
"3" "Enable detailed dxvk hud, gallium fps counter"
	case $? in
	1)
		echo "unset GALLIUM_HUD
export GALLIUM_HUD_PERIOD=1
unset DXVK_HUD">$PREFIX/glibc/opt/conf/hud.conf
	;;
	2)
		echo "export GALLIUM_HUD=simple,fps
export GALLIUM_HUD_PERIOD=1
export DXVK_HUD=version,fps,scale=0.7">$PREFIX/glibc/opt/conf/hud.conf
	;;
	3)
		echo "export GALLIUM_HUD=simple,fps
export GALLIUM_HUD_PERIOD=1
export DXVK_HUD=version,fps,api,scale=0.7,devinfo,gpuload,frametimes">$PREFIX/glibc/opt/conf/hud.conf
	;;
	esac
;;
5)
	dialog_menu "" "" \
"1" "TU_DEBUG=noconform" \
"2" "TU_DEBUG=noconform,syncdraw (slow)" \
"3" "TU_DEBUG=noconform,syncdraw,flushall (slower)"
	case $? in
	1)
		echo "export TU_DEBUG=noconform">$PREFIX/glibc/opt/conf/tu_debug.conf
	;;
	2)
		echo "export TU_DEBUG=noconform,syncdraw">$PREFIX/glibc/opt/conf/tu_debug.conf
	;;
	3)
		echo "export TU_DEBUG=noconform,syncdraw,flushall">$PREFIX/glibc/opt/conf/tu_debug.conf
	;;
	esac
;;
6)
	cp $PREFIX/glibc/opt/default-conf/conf/{cores.conf,hud.conf,tu_debug.conf,wsi_present.conf} $PREFIX/glibc/opt/conf
	cp $PREFIX/glibc/opt/default-conf/{last-resolution.conf,locale.conf} $PREFIX/glibc/opt
;;
255)
	break
;;
esac
done
