#!/bin/bash

defitem=1

while true; do
load_configs
dialog_menu_item $defitem "Dynarec preset" "\ZbCurrent settings:\Z3
    DYNAREC_ALIGNED_ATOMICS = \Zb$BOX64_DYNAREC_ALIGNED_ATOMICS\Z3
    BOX86_DYNAREC_BIGBLOCK = \Zb$BOX86_DYNAREC_BIGBLOCK\Z3
    BOX64_DYNAREC_BIGBLOCK = $BOX64_DYNAREC_BIGBLOCK\Z3
    DYNAREC_FASTNAN = \Zb$BOX64_DYNAREC_FASTNAN\Z3
    DYNAREC_SAFEFLAGS = \Zb$BOX64_DYNAREC_SAFEFLAGS\Z3
    DYNAREC_STRONGMEM = \Zb$BOX64_DYNAREC_STRONGMEM\Z3
    DYNAREC_WAIT = \Zb$BOX64_DYNAREC_WAIT\Z3
    DYNAREC_X87DOUBLE = \Zb$BOX64_DYNAREC_X87DOUBLE\Z3
    DYNAREC_CALLRET = \Zb$BOX64_DYNAREC_CALLRET\Zn" \
    "1" "Deus Ex Human Revolution" \
    "2" "Resident Evil 6" \

defitem=$?
case $defitem in
1)
	echo "export BOX86_DYNAREC_ALIGNED_ATOMICS=1
export BOX64_DYNAREC_ALIGNED_ATOMICS=1">$PREFIX/glibc/opt/conf/dynarec/aligned_atomics.conf
	echo "export BOX86_DYNAREC_BIGBLOCK=$BOX86_DYNAREC_BIGBLOCK
export BOX64_DYNAREC_BIGBLOCK=2">$PREFIX/glibc/opt/conf/dynarec/bigblock.conf
	echo "export BOX86_DYNAREC_BIGBLOCK=
export BOX64_DYNAREC_BIGBLOCK=$BOX64_DYNAREC_BIGBLOCK">$PREFIX/glibc/opt/conf/dynarec/bigblock.conf
	echo "export BOX86_DYNAREC_FASTNAN=1
export BOX64_DYNAREC_FASTNAN=1">$PREFIX/glibc/opt/conf/dynarec/fastnan.conf
	echo "unset BOX86_DYNAREC_SAFEFLAGS
unset BOX64_DYNAREC_SAFEFLAGS">$PREFIX/glibc/opt/conf/dynarec/safeflags.conf
	echo "unset BOX86_DYNAREC_STRONGMEM
unset BOX64_DYNAREC_STRONGMEM">$PREFIX/glibc/opt/conf/dynarec/strongmem.conf
	echo "unset BOX86_DYNAREC_WAIT
unset BOX64_DYNAREC_WAIT">$PREFIX/glibc/opt/conf/dynarec/wait.conf
	echo "unset BOX86_DYNAREC_X87DOUBLE
unset BOX64_DYNAREC_X87DOUBLE">$PREFIX/glibc/opt/conf/dynarec/x87double.conf
	echo "export BOX86_DYNAREC_CALLRET=0
export BOX64_DYNAREC_CALLRET=0">$PREFIX/glibc/opt/conf/dynarec/callret.conf
;;
2)
	echo "export BOX86_DYNAREC_ALIGNED_ATOMICS=1
export BOX64_DYNAREC_ALIGNED_ATOMICS=1">$PREFIX/glibc/opt/conf/dynarec/aligned_atomics.conf
	echo "export BOX86_DYNAREC_BIGBLOCK=$BOX86_DYNAREC_BIGBLOCK
export BOX64_DYNAREC_BIGBLOCK=2">$PREFIX/glibc/opt/conf/dynarec/bigblock.conf
	echo "export BOX86_DYNAREC_BIGBLOCK=2
export BOX64_DYNAREC_BIGBLOCK=$BOX64_DYNAREC_BIGBLOCK">$PREFIX/glibc/opt/conf/dynarec/bigblock.conf
	echo "export BOX86_DYNAREC_FASTNAN=1
export BOX64_DYNAREC_FASTNAN=1">$PREFIX/glibc/opt/conf/dynarec/fastnan.conf
	echo "export BOX86_DYNAREC_SAFEFLAGS=1
export BOX64_DYNAREC_SAFEFLAGS=1">$PREFIX/glibc/opt/conf/dynarec/safeflags.conf
	echo "export BOX86_DYNAREC_STRONGMEM=0
export BOX64_DYNAREC_STRONGMEM=0">$PREFIX/glibc/opt/conf/dynarec/strongmem.conf
	echo "export BOX86_DYNAREC_WAIT=0
export BOX64_DYNAREC_WAIT=0">$PREFIX/glibc/opt/conf/dynarec/wait.conf
	echo "export BOX86_DYNAREC_X87DOUBLE=0
export BOX64_DYNAREC_X87DOUBLE=0">$PREFIX/glibc/opt/conf/dynarec/x87double.conf
	echo "export BOX86_DYNAREC_CALLRET=1
export BOX64_DYNAREC_CALLRET=1">$PREFIX/glibc/opt/conf/dynarec/callret.conf
;;
255)
	break
;;
esac
done
